### ISSUE TITLE
Почему вы настоятельно рекомендуте Виктору отказаться от margin-top?

### ISSUE THREAD

**Issue by DenisVASI9** [bringmetheaugust/Beria#1]

**Comment by bringmetheaugust** [comment]
@DenisVASI9 некоторые умные люди полагают, что все елементы дизайна должны иметь отступы **по всем** границам своего контента или **по определенной оси**. например, список `ul` c элементами `li`, которые имеют отступы между собой:
* **правильно**
```li { padding: 10px 0; }```
* **неправильно**
``` li { padding-top: 20px; } ```

если соблюдать этот принцип в дизайне, то и при верстке будет намного проще и чище код.    
но стоит уточнить, что это субъективный взгляд на ситуацию в целом
